imports:
    - { resource: ../docs/components.yaml }
    - { resource: ../docs/paths.yaml }

nelmio_api_doc:
    documentation:
        info:
            title: Booxit
            description: API Documentation
            version: 1.0.0
        security:
            - Bearer: []
        tags:
        - name: Auth
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc