services:
  nginx:
    hostname: booxit-backend-nginx
    networks:
      - proxy

  database:
    hostname: booxit-backend-db
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true